apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: breakglass
subjects:
  - kind: ServiceAccount
    name: breakglass
    namespace: default
roleRef:
  kind: ClusterRole
  name: breakglass
  apiGroup: rbac.authorization.k8s.io
