breakglass:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 0
  type: ClusterIP
webhookService:
  type: ClusterIP
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 9443
config:
  configYaml: |-
    server:
      listenAddress: 0.0.0.0:8081
    authorizationServer:
      url: http://127.0.0.1:8080
      jwksEndpoint: "realms/master/protocol/openid-connect/certs" # sample for keycloak
    frontend:
      oidcAuthority: http://127.0.0.1:8080/realms/master
      oidcClientID: breakglass-ui
      baseURL: http://localhost:5173
    mail:
      host: 172.18.0.2
      port: 1025
      insecureSkipVerify: true
    kubernetes:
      context: ""
      oidcPrefixes:
      - "oidc:"
      # Interval for periodic ClusterConfig validation. Example: "10m"
      clusterConfigCheckInterval: "10m"
kubernetesClusterDomain: cluster.local
manager:
  breakglass:
    env:
      breakglassConfigPath: /config/config.yaml
      enableWebhookManager: "true"
    image:
      repository: harbor.das-schiff.telekom.de/schiff-dev/breakglass-2
      tag: latest
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    fsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""

ingress:
  enabled: false
  # host (FQDN) for the ingress
  host: breakglass.example.com
  # optional annotations map to be added to the ingress metadata
  annotations: {}
  tls:
    enabled: false
    # secretName containing TLS cert for the provided host(s)
    secretName: ""
    # hosts list for TLS entry
    hosts:
      - breakglass.example.com
