apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "breakglass-controller.fullname" . }}-config
  labels:
  {{- include "breakglass-controller.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config.configYaml | toYaml | indent 1 }}
