apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "breakglass-controller.fullname" . }}-manager-session-rolebinding
  labels:
  {{- include "breakglass-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "breakglass-controller.fullname" . }}-session-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "breakglass-controller.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
