apiVersion: v1
kind: Service
metadata:
  name: {{ include "breakglass-controller.fullname" . }}-webhook-service
  labels:
    app: breakglass
  {{- include "breakglass-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app: breakglass
    {{- include "breakglass-controller.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
