apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "breakglass-controller.fullname" . }}-webhook-cert-rotator-role-binding
  labels:
  {{- include "breakglass-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "breakglass-controller.fullname" . }}-webhook-cert-rotator-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "breakglass-controller.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
