apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "breakglass-controller.fullname" . }}-webhook-cert-rotator-cluster-role
  labels:
  {{- include "breakglass-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - validating-webhook-configuration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - patch
