---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-breakglassescalation
  failurePolicy: Fail
  name: breakglassescalation.validation.breakglass.t-caas.telekom.com
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - breakglassescalations
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-breakglasssession
  failurePolicy: Fail
  name: breakglasssession.validation.breakglass.t-caas.telekom.com
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - breakglasssessions
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-clusterconfig
  failurePolicy: Fail
  name: clusterconfig.validation.breakglass.t-caas.telekom.com
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-identityprovider
  failurePolicy: Fail
  name: identityprovider.validation.breakglass.t-caas.telekom.com
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - identityproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-mailprovider
  failurePolicy: Fail
  name: mailprovider.validation.breakglass.t-caas.telekom.com
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mailproviders
  sideEffects: None
