---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: breakglass-validating-session-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: breakglass-webhook-service
      namespace: breakglass-system
      port: 443
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-breakglasssession
  failurePolicy: Fail
  name: vbreakglasssession.kb.io
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - breakglasssessions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: breakglass-validating-escalation-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: breakglass-webhook-service
      namespace: breakglass-system
      port: 443
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-breakglassescalation
  failurePolicy: Fail
  name: vbreakglassescalation.kb.io
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - breakglassescalations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: breakglass-validating-clusterconfig-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: breakglass-webhook-service
      namespace: breakglass-system
      port: 443
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-clusterconfig
  failurePolicy: Fail
  name: vclusterconfig.kb.io
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: breakglass-validating-identityprovider-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: breakglass-webhook-service
      namespace: breakglass-system
      path: /validate-breakglass-t-caas-telekom-com-v1alpha1-identityprovider
  failurePolicy: Fail
  name: videntityprovider.kb.io
  rules:
  - apiGroups:
    - breakglass.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - identityproviders
  sideEffects: None
