# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditconfig-manager-role
rules:
- apiGroups:
  - breakglass.t-caas.telekom.com
  resources:
  - auditconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - breakglass.t-caas.telekom.com
  resources:
  - auditconfigs/status
  verbs:
  - get
  - patch
  - update
