apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: escalation-manager-role
rules:
- apiGroups:
  - telekom.breakglass.de
  resources:
  - breakglassescalations
  verbs:
  - get
  - list
  - watch
