apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: session-manager-role
rules:
- apiGroups:
  - breakglass.t-caas.telekom.com
  resources:
  - breakglasssessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - breakglass.t-caas.telekom.com
  resources:
  - breakglasssessions/status
  verbs:
  - get
  - update
  - create
