apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: breakglass-identity-provider-manager-role-binding
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: breakglass-system
roleRef:
  kind: ClusterRole
  name: breakglass-identity-provider-manager-role
  apiGroup: rbac.authorization.k8s.io
