resources:
- service_account.yaml
- breakglassescalation_role.yaml
- breakglasssession_role.yaml
- breakglassescalation_role_binding.yaml
- breakglasssession_role_binding.yaml
- impersonate_role.yaml
- impersonate_role_binding.yaml
- secrets_reader_role.yaml
- secrets_reader_role_binding.yaml
- identityprovider_role.yaml
- identityprovider_role_binding.yaml
- webhook_cert_rotator_role.yaml
