resources:
- service_account.yaml
- auditconfig_role.yaml
- auditconfig_role_binding.yaml
- breakglassescalation_role.yaml
- breakglasssession_role.yaml
- breakglassescalation_role_binding.yaml
- breakglasssession_role_binding.yaml
- debugsession_role.yaml
- debugsession_role_binding.yaml
- impersonate_role.yaml
- impersonate_role_binding.yaml
- secrets_role.yaml
- secrets_role_binding.yaml
- identityprovider_role.yaml
- identityprovider_role_binding.yaml
- mailprovider_role.yaml
- mailprovider_role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- validatingwebhookconfigurations_role.yaml
- validatingwebhookconfigurations_role_binding.yaml
