apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: breakglass-manager-secrets-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: breakglass-secrets-reader-role
subjects:
- kind: ServiceAccount
  name: breakglass-manager
  namespace: breakglass-system
