apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: validatingwebhookconfigurations-manager-role
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "update", "watch"]
