# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: breakglass.t-caas.telekom.com/v1alpha1
kind: BreakglassSession 
metadata:
  labels:
  name: kind-tester-breakglass-service-create-1 
spec:
  cluster: kind
  user: tester@mail.com
  grantedGroup: breakglass-service-create
