apiVersion: breakglass.t-caas.telekom.com/v1alpha1
kind: BreakglassEscalation 
metadata:
  labels:
  name: kind-sample
spec:
  escalatedGroup: "breakglass-create-all"
  allowed:
    clusters: ["kind"]
    users: ["tester@mail.com"]
    groups: ["system:authenticated"]
  approvers:
    users: ["admin@mail.com"]
