apiVersion: telekom.breakglass.de/v1alpha1
kind: BreakglassSession 
metadata:
  labels:
  name: kind-tester-breakglass-service-create-1 
spec:
  cluster: kind
  username: tester
  group: breakglass-service-create
