# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: breakglass-webhook
webhooks:
  - name: breakglass-webhook.default.svc.cluster.local
    clientConfig:
      service:
        name: breakglass-webhook
        namespace: default
        path: "/mutate"
      caBundle: <reference-to-secret>
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: [""]
        apiVersions: ["*"]
        resources: ["*"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
