# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: system
  labels:
    app: breakglass
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breakglass
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: breakglass
    spec:
      containers:
        - image: breakglass:e2e
          imagePullPolicy: "Always"
          name: breakglass
          resources: {}
          env:
            - name: BREAKGLASS_CONFIG_PATH
              value: /config/config.yaml
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /config/
              name: config
              readOnly: true
      serviceAccountName: manager
      volumes:
      - name: config
        configMap:
          name: config
