apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: breakglass-ingress
  labels:
    app.kubernetes.io/name: myingress
spec:
  rules:
  - host: breakglass.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: breakglass
            port:
              name: http
