resources:
- app.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: breakglass
  newName: harbor.das-schiff.telekom.de/schiff-dev/breakglass-2
  newTag: latest
- name: controller
  newName: harbor.das-schiff.telekom.de/schiff-dev/breakglass-2
  newTag: latest
