resources:
- app.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: breakglass
  newName: breakglass
  newTag: latest
- name: controller
  newName: breakglass
  newTag: latest
