- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: certs
    configMap:
     name: breakglass-certs

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /certs/
    name: certs
    readOnly: true
