# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: certs
    configMap:
     name: breakglass-dev-certs

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /certs/
    name: certs
    readOnly: true
