configMapGenerator:
- name: breakglass-dev-config
  namespace: breakglass-dev-system
  behavior: replace
  literals:
  - server=newval1
- name: config
  namespace: system
  behavior: replace
  literals:
  - server=newval1

