apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: breakglass-dev-system
  labels:
    app: mailhog
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:v1.0.1
        ports:
        - containerPort: 1025
        - containerPort: 8025
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
  namespace: breakglass-dev-system
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8025
    protocol: TCP
    targetPort: 8025
    name: http
  - port: 1025
    protocol: TCP
    targetPort: 1025
    name: smtp
  selector:
    app: mailhog
  sessionAffinity: None
  type: ClusterIP
