apiVersion: breakglass.t-caas.telekom.com/v1alpha1
kind: MailProvider
metadata:
  name: mailhog
spec:
  displayName: "Development MailHog"
  default: true
  smtp:
    host: breakglass-mailhog.breakglass-system.svc.cluster.local
    port: 1025
    insecureSkipVerify: true
  sender:
    address: noreply@breakglass.local
    name: "Breakglass Dev"
  retry:
    count: 3
    initialBackoffMs: 100
    queueSize: 1000
