apiVersion: apps/v1
kind: Deployment
metadata:
  name: breakglass-manager
  namespace: breakglass-system
spec:
  template:
    spec:
      containers:
      - name: breakglass
        image: breakglass:e2e
        imagePullPolicy: IfNotPresent
        args: ["--debug"]
        resources: {}
