# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: escalation-config
description: Helm chart to create BreakglassEscalation and ClusterConfig CRs for testing
type: application
version: 0.2.1
appVersion: "0.1.0"
