---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: breakglassescalations.breakglass.t-caas.telekom.com
spec:
  group: breakglass.t-caas.telekom.com
  names:
    kind: BreakglassEscalation
    listKind: BreakglassEscalationList
    plural: breakglassescalations
    singular: breakglassescalation
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BreakglassEscalationSpec defines the desired state of BreakglassEscalation.
            properties:
              allowed:
                description: allowed specifies who is allowed to use this escalation.
                properties:
                  clusters:
                    description: |-
                      clusters is a list of clusters this escalation can be used for.
                      todo: implement globbing (or regex?) support
                    items:
                      type: string
                    type: array
                  groups:
                    description: |-
                      groups is a list of groups this escalation can be used by.
                      todo: implement globbing (or regex?) support
                    items:
                      type: string
                    type: array
                  users:
                    description: |-
                      users is a list of users this escalation can be used by.
                      todo: implement globbing (or regex?) support
                    items:
                      type: string
                    type: array
                type: object
              approvers:
                description: approvers specifies who is allowed to approve this escalation.
                properties:
                  groups:
                    description: groups that are allowed to approve a session for
                      this escalation
                    items:
                      type: string
                    type: array
                  users:
                    description: users that are allowed to approve a session for this
                      escalation
                    items:
                      type: string
                    type: array
                type: object
              escalatedGroup:
                description: escalatedGroup is the group to be granted by this escalation.
                type: string
              idleTimeout:
                default: 1h
                description: idleTimeout is the maximum amount of time a session for
                  this escalation can sit idle without being used.
                type: string
              maxValidFor:
                default: 1h
                description: maxValidFor is the maximum amount of time a session for
                  this escalation will be active for after it is approved.
                type: string
              retainFor:
                description: retainFor is the amount of time to wait before removing
                  a session for this escalation after it expired
                type: string
            required:
            - allowed
            type: object
          status:
            description: BreakglassEscalationStatus defines the observed state of
              BreakglassEscalation.
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
