name: Security Scan
permissions:
  contents: read

on:
  pull_request:
    branches: [main ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Build image (local)
        run: docker build -t breakglass:scan .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: breakglass:scan
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
      - name: Upload SBOM
        uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        id: sbom
        with:
          image: breakglass:scan
          format: spdx-json
          output-file: sbom-spdx.json

      - name: Upload SBOM artifact
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: security-sbom
          path: sbom-spdx.json