# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Security Scan
permissions:
  contents: read

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image (local)
        run: docker build -t breakglass:scan .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: breakglass:scan
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
      - name: Upload SBOM
        uses: anchore/sbom-action@v0.17.6
        with:
          image: breakglass:scan
          format: spdx-json
          artifact-name: sbom-spdx.json